name-template: '$RESOLVED_VERSION 🌈'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '❗ Breaking Changes'
    labels:
      - 'breaking'
      - 'breaking changes'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐞 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '⬆️ Dependencies'
    collapse-after: 3
    labels:
      - 'dependencies'
exclude-labels:
  - 'skip-changelog'
  - 'chore'
  - 'test'
sort-by: title
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
header: |
  # What's Changed
  
template: |
  $CHANGES
footer: | 
  
  特此感谢 `$REPOSITORY` 本次版本发布的代码贡献者： 
  $CONTRIBUTORS。
